#!/usr/bin/env node
/**
 * Generates a deterministic e-Stat-shaped fixture at public/datastore/processingData.json
 * so local dev and CI can run the dashboard without the ESTAT_APP_ID secret.
 * Mirrors e-Stat semantics: parent bureaus report totals that INCLUDE their
 * branch offices, and the nationwide row is the sum of every leaf bureau
 * (correctBureauAggregates subtracts branches back out at load time).
 *
 * Usage: node scripts/generate-fixture.mjs [outPath]
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = process.argv[2] ?? 'public/datastore/processingData.json';

// Parent -> branch offices (from src/constants/bureauOptions.ts)
const CHILDREN = {
  101720: ['101740'], // Fukuoka > Naha
  101350: ['101370'], // Nagoya > Chubu Airport
  101460: ['101480', '101490'], // Osaka > Kansai Airport, Kobe
  101170: ['101190', '101200', '101210'], // Shinagawa > Narita, Haneda, Yokohama
};
const ALL_BUREAUS = [
  '101720', '101580', '101490', '101350', '101740', '101460', '101010', '101090',
  '101170', '101670', '101210', '101190', '101200', '101480', '101370',
];
const NATIONWIDE = '100000';
const TYPES = ['10', '20', '30', '40', '50', '60'];

// Relative scale per bureau so Tokyo dwarfs Naha, like reality
const SCALE = {
  101170: 30, 101460: 14, 101350: 9, 101090: 6, 101010: 4, 101720: 5,
  101580: 3, 101670: 3, 101490: 2, 101190: 2, 101200: 2, 101210: 4,
  101740: 1, 101370: 1, 101480: 1,
};
// Relative volume per application type (Extension/Change dominate)
const TYPE_SCALE = { 10: 2, 20: 10, 30: 5, 40: 2, 50: 1, 60: 4 };

// Deterministic LCG so the fixture never churns in git
let seed = 20260726;
const rand = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);

const MONTHS = [];
for (let y = 2022, m = 11; !(y === 2025 && m === 11); m === 12 ? (y++, (m = 1)) : m++) {
  MONTHS.push({ y, m });
}

const VALUE = [];
const push = (time, bureau, type, status, value) =>
  VALUE.push({ '@tab': '100', '@cat01': status, '@cat02': type, '@cat03': bureau, '@time': time, $: String(Math.max(0, Math.round(value))), '@unit': '件' });

for (const { y, m } of MONTHS) {
  const time = `${y}0007${String(m).padStart(2, '0')}`;
  const seasonal = 1 + 0.35 * Math.sin(((m - 3) / 12) * 2 * Math.PI); // spring surge
  for (const type of TYPES) {
    // per-leaf base numbers for this month/type
    const base = {};
    for (const b of ALL_BUREAUS) {
      const volume = 220 * SCALE[b] * TYPE_SCALE[type] * seasonal * (0.85 + 0.3 * rand());
      const oldApps = volume * (0.55 + 0.2 * rand());
      const newApps = volume;
      const processed = (oldApps + newApps) * (0.42 + 0.16 * rand());
      const denied = processed * (0.015 + 0.01 * rand());
      const other = processed * (0.02 + 0.01 * rand());
      base[b] = { oldApps, newApps, processed, denied, other };
    }
    // parent rows include their branches (e-Stat aggregate semantics)
    const rows = {};
    for (const b of ALL_BUREAUS) {
      const own = base[b];
      const kids = CHILDREN[b] ?? [];
      rows[b] = Object.fromEntries(
        Object.keys(own).map((k) => [k, own[k] + kids.reduce((s, c) => s + base[c][k], 0)])
      );
    }
    rows[NATIONWIDE] = Object.fromEntries(
      Object.keys(base[ALL_BUREAUS[0]]).map((k) => [k, ALL_BUREAUS.reduce((s, b) => s + base[b][k], 0)])
    );

    for (const [bureau, r] of Object.entries(rows)) {
      const granted = r.processed - r.denied - r.other;
      push(time, bureau, type, '102000', r.oldApps);
      push(time, bureau, type, '103000', r.newApps);
      push(time, bureau, type, '100000', r.oldApps + r.newApps);
      push(time, bureau, type, '300000', r.processed);
      push(time, bureau, type, '301000', granted);
      push(time, bureau, type, '302000', r.denied);
      push(time, bureau, type, '305000', r.other);
    }
  }
}

const fixture = {
  GET_STATS_DATA: {
    RESULT: { STATUS: 0, DATE: '2026-07-26' },
    STATISTICAL_DATA: {
      TABLE_INF: { SURVEY_DATE: MONTHS.at(-1).y * 100 + MONTHS.at(-1).m, note: 'FIXTURE — generated by scripts/generate-fixture.mjs' },
      DATA_INF: { VALUE },
    },
  },
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(fixture));
console.log(`wrote ${OUT}: ${VALUE.length} values, ${MONTHS.length} months`);
